# {    
#     "username" : "噬菌体",
#     "password" : "123",
#     "mobile" : "19900001234",
#     "signature" : "猪突猛进！",
#     "hex" : "d6fe8c82fb0abac17a702fd2a94eff37",
#     "stuNo" : "2016s03953"
# }



POST http://localhost:3000/api/login
content-type: application/json

{
    "stuNo":"111","password":"123"
}




######
######
POST http://localhost:3000/api/register
content-type: application/json

{
    "username":"zhang",
    "password":"123",
    "mobile" : "19900001234",
    "stuNo": "11123333-"
}




######
######
GET http://localhost:3000/api/user/getInfo?stuNo=2012623053

###
POST http://localhost:3000/api/user/changePassword
content-type: application/json

{
    "newPwd":"12322s22-",
    "stuNo" : "2012623053"
}



######
######
POST http://localhost:3000/api/user/changeInfo
content-type: application/json

{
    "username":"zhang3sss",
    "mobile" : "19900001234",
    "stuNo" : "111",
    "signature" : "猪突猛进-----------！!!!"
}



######
######
GET http://localhost:3000/api/evaluation/getRatingScale?type=SAS

######
######
POST http://localhost:3000/api/evaluation/postAnswer
content-type: application/json

{
    "answer": [1,0,1,2,1,0],
    "type": "Sssssss-"
}
